# Generated by Django 2.0.4 on 2018-04-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False, editable=False)),
                ('refreshed', models.DateTimeField(default=None, editable=False, null=True)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'enable', 'disable'),
            },
        ),
    ]
